// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrzykładoweKolokwiumZAPBD_EF_.Models;

namespace PrzykładoweKolokwiumZAPBD_EF_.Migrations
{
    [DbContext(typeof(BakeryDBContext))]
    [Migration("20200609210029_AddedDbSetsToContext")]
    partial class AddedDbSetsToContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.Klient", b =>
                {
                    b.Property<int>("IdKlient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("IdKlient");

                    b.ToTable("Klients");
                });

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.Pracownik", b =>
                {
                    b.Property<int>("IdPracownik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("IdPracownik");

                    b.ToTable("Pracowniks");
                });

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.WyrobCukierniczy", b =>
                {
                    b.Property<int>("IdWyrobCukierniczy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("CenaZaSzt")
                        .HasColumnType("real");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdWyrobCukierniczy");

                    b.ToTable("WyrobCukierniczies");
                });

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.Zamowienie", b =>
                {
                    b.Property<int>("IdZamowienie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataPrzyjecia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRealizacji")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdKlient")
                        .HasColumnType("int");

                    b.Property<int>("IdPracownik")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("IdZamowienie");

                    b.HasIndex("IdKlient");

                    b.HasIndex("IdPracownik");

                    b.ToTable("Zamowienies");
                });

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.ZamowienieWyrobCukierniczy", b =>
                {
                    b.Property<int>("IdZamowienia")
                        .HasColumnType("int");

                    b.Property<int>("IdwyrobuCukierniczego")
                        .HasColumnType("int");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("IdZamowienia", "IdwyrobuCukierniczego");

                    b.HasIndex("IdwyrobuCukierniczego");

                    b.ToTable("Zamowienie_WyrobCukierniczy");
                });

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.Zamowienie", b =>
                {
                    b.HasOne("PrzykładoweKolokwiumZAPBD_EF_.Models.Klient", "Klient")
                        .WithMany("Zamowienies")
                        .HasForeignKey("IdKlient")
                        .IsRequired();

                    b.HasOne("PrzykładoweKolokwiumZAPBD_EF_.Models.Pracownik", "Pracownik")
                        .WithMany("Zamowienies")
                        .HasForeignKey("IdPracownik")
                        .IsRequired();
                });

            modelBuilder.Entity("PrzykładoweKolokwiumZAPBD_EF_.Models.ZamowienieWyrobCukierniczy", b =>
                {
                    b.HasOne("PrzykładoweKolokwiumZAPBD_EF_.Models.Zamowienie", "Zamowienie")
                        .WithMany("ZamowienieWyrobCukierniczies")
                        .HasForeignKey("IdZamowienia")
                        .IsRequired();

                    b.HasOne("PrzykładoweKolokwiumZAPBD_EF_.Models.WyrobCukierniczy", "WyrobCukierniczy")
                        .WithMany("ZamowienieWyrobCukierniczies")
                        .HasForeignKey("IdwyrobuCukierniczego")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
